# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scythe_pb2 as scythe__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scythe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorServiceStub(object):
    """Most RPCs require `authorization: Bearer <session_token>` in gRPC metadata.
    The TokenAuthInterceptor validates every call against the orchestrator's
    shared session registry.  Exceptions:
    AuthService.Login    — unauthenticated (used to obtain a token)
    OperatorStream.Connect — starts anonymous, upgrades in-place via AuthRequest

    ── Orchestrator Service ─────────────────────────────────────────────────────
    Instance lifecycle operations. Handled by the orchestrator process.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListInstances = channel.unary_unary(
                '/scythe.v1.OrchestratorService/ListInstances',
                request_serializer=scythe__pb2.ListInstancesRequest.SerializeToString,
                response_deserializer=scythe__pb2.ListInstancesResponse.FromString,
                _registered_method=True)
        self.DeployObserver = channel.unary_unary(
                '/scythe.v1.OrchestratorService/DeployObserver',
                request_serializer=scythe__pb2.DeployRequest.SerializeToString,
                response_deserializer=scythe__pb2.DeployResponse.FromString,
                _registered_method=True)
        self.TerminateInstance = channel.unary_unary(
                '/scythe.v1.OrchestratorService/TerminateInstance',
                request_serializer=scythe__pb2.TerminateRequest.SerializeToString,
                response_deserializer=scythe__pb2.TerminateResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/scythe.v1.OrchestratorService/GetHealth',
                request_serializer=scythe__pb2.HealthRequest.SerializeToString,
                response_deserializer=scythe__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamInstanceUpdates = channel.unary_stream(
                '/scythe.v1.OrchestratorService/StreamInstanceUpdates',
                request_serializer=scythe__pb2.StreamRequest.SerializeToString,
                response_deserializer=scythe__pb2.InstanceUpdate.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """Most RPCs require `authorization: Bearer <session_token>` in gRPC metadata.
    The TokenAuthInterceptor validates every call against the orchestrator's
    shared session registry.  Exceptions:
    AuthService.Login    — unauthenticated (used to obtain a token)
    OperatorStream.Connect — starts anonymous, upgrades in-place via AuthRequest

    ── Orchestrator Service ─────────────────────────────────────────────────────
    Instance lifecycle operations. Handled by the orchestrator process.

    """

    def ListInstances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployObserver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInstanceUpdates(self, request, context):
        """Server-streaming: pushes instance status updates every poll cycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstances,
                    request_deserializer=scythe__pb2.ListInstancesRequest.FromString,
                    response_serializer=scythe__pb2.ListInstancesResponse.SerializeToString,
            ),
            'DeployObserver': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployObserver,
                    request_deserializer=scythe__pb2.DeployRequest.FromString,
                    response_serializer=scythe__pb2.DeployResponse.SerializeToString,
            ),
            'TerminateInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateInstance,
                    request_deserializer=scythe__pb2.TerminateRequest.FromString,
                    response_serializer=scythe__pb2.TerminateResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=scythe__pb2.HealthRequest.FromString,
                    response_serializer=scythe__pb2.HealthResponse.SerializeToString,
            ),
            'StreamInstanceUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInstanceUpdates,
                    request_deserializer=scythe__pb2.StreamRequest.FromString,
                    response_serializer=scythe__pb2.InstanceUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scythe.v1.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scythe.v1.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """Most RPCs require `authorization: Bearer <session_token>` in gRPC metadata.
    The TokenAuthInterceptor validates every call against the orchestrator's
    shared session registry.  Exceptions:
    AuthService.Login    — unauthenticated (used to obtain a token)
    OperatorStream.Connect — starts anonymous, upgrades in-place via AuthRequest

    ── Orchestrator Service ─────────────────────────────────────────────────────
    Instance lifecycle operations. Handled by the orchestrator process.

    """

    @staticmethod
    def ListInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scythe.v1.OrchestratorService/ListInstances',
            scythe__pb2.ListInstancesRequest.SerializeToString,
            scythe__pb2.ListInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployObserver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scythe.v1.OrchestratorService/DeployObserver',
            scythe__pb2.DeployRequest.SerializeToString,
            scythe__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scythe.v1.OrchestratorService/TerminateInstance',
            scythe__pb2.TerminateRequest.SerializeToString,
            scythe__pb2.TerminateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scythe.v1.OrchestratorService/GetHealth',
            scythe__pb2.HealthRequest.SerializeToString,
            scythe__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInstanceUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.OrchestratorService/StreamInstanceUpdates',
            scythe__pb2.StreamRequest.SerializeToString,
            scythe__pb2.InstanceUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HypergraphServiceStub(object):
    """── Hypergraph Service ───────────────────────────────────────────────────────
    Per-instance data plane: snapshots and streaming graph deltas.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSnapshot = channel.unary_unary(
                '/scythe.v1.HypergraphService/GetSnapshot',
                request_serializer=scythe__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=scythe__pb2.HypergraphSnapshot.FromString,
                _registered_method=True)
        self.StreamGraphDeltas = channel.unary_stream(
                '/scythe.v1.HypergraphService/StreamGraphDeltas',
                request_serializer=scythe__pb2.GraphStreamRequest.SerializeToString,
                response_deserializer=scythe__pb2.GraphDelta.FromString,
                _registered_method=True)


class HypergraphServiceServicer(object):
    """── Hypergraph Service ───────────────────────────────────────────────────────
    Per-instance data plane: snapshots and streaming graph deltas.

    """

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGraphDeltas(self, request, context):
        """Server-streaming: incremental graph events since `since_seq`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HypergraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=scythe__pb2.SnapshotRequest.FromString,
                    response_serializer=scythe__pb2.HypergraphSnapshot.SerializeToString,
            ),
            'StreamGraphDeltas': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGraphDeltas,
                    request_deserializer=scythe__pb2.GraphStreamRequest.FromString,
                    response_serializer=scythe__pb2.GraphDelta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scythe.v1.HypergraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scythe.v1.HypergraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HypergraphService(object):
    """── Hypergraph Service ───────────────────────────────────────────────────────
    Per-instance data plane: snapshots and streaming graph deltas.

    """

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scythe.v1.HypergraphService/GetSnapshot',
            scythe__pb2.SnapshotRequest.SerializeToString,
            scythe__pb2.HypergraphSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGraphDeltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.HypergraphService/StreamGraphDeltas',
            scythe__pb2.GraphStreamRequest.SerializeToString,
            scythe__pb2.GraphDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClusterIntelServiceStub(object):
    """── Cluster Intelligence Service ─────────────────────────────────────────────
    Per-instance data plane: Latent Swarm Decomposition Engine.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DecomposeCluster = channel.unary_unary(
                '/scythe.v1.ClusterIntelService/DecomposeCluster',
                request_serializer=scythe__pb2.ClusterRequest.SerializeToString,
                response_deserializer=scythe__pb2.ClusterDecomposition.FromString,
                _registered_method=True)
        self.StreamAutopsy = channel.unary_stream(
                '/scythe.v1.ClusterIntelService/StreamAutopsy',
                request_serializer=scythe__pb2.ClusterRequest.SerializeToString,
                response_deserializer=scythe__pb2.AutopsyEvent.FromString,
                _registered_method=True)


class ClusterIntelServiceServicer(object):
    """── Cluster Intelligence Service ─────────────────────────────────────────────
    Per-instance data plane: Latent Swarm Decomposition Engine.

    """

    def DecomposeCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAutopsy(self, request, context):
        """Server-streaming: live autopsy events (intent, ASN shift, activation pulse).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterIntelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DecomposeCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.DecomposeCluster,
                    request_deserializer=scythe__pb2.ClusterRequest.FromString,
                    response_serializer=scythe__pb2.ClusterDecomposition.SerializeToString,
            ),
            'StreamAutopsy': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAutopsy,
                    request_deserializer=scythe__pb2.ClusterRequest.FromString,
                    response_serializer=scythe__pb2.AutopsyEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scythe.v1.ClusterIntelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scythe.v1.ClusterIntelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterIntelService(object):
    """── Cluster Intelligence Service ─────────────────────────────────────────────
    Per-instance data plane: Latent Swarm Decomposition Engine.

    """

    @staticmethod
    def DecomposeCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scythe.v1.ClusterIntelService/DecomposeCluster',
            scythe__pb2.ClusterRequest.SerializeToString,
            scythe__pb2.ClusterDecomposition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAutopsy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.ClusterIntelService/StreamAutopsy',
            scythe__pb2.ClusterRequest.SerializeToString,
            scythe__pb2.AutopsyEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ScytheStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamClusters = channel.unary_stream(
                '/scythe.v1.ScytheStreamService/StreamClusters',
                request_serializer=scythe__pb2.StreamRequest.SerializeToString,
                response_deserializer=scythe__pb2.StreamCluster.FromString,
                _registered_method=True)
        self.StreamRFField = channel.unary_stream(
                '/scythe.v1.ScytheStreamService/StreamRFField',
                request_serializer=scythe__pb2.LodHint.SerializeToString,
                response_deserializer=scythe__pb2.RFField.FromString,
                _registered_method=True)
        self.StreamDeltas = channel.unary_stream(
                '/scythe.v1.ScytheStreamService/StreamDeltas',
                request_serializer=scythe__pb2.StreamRequest.SerializeToString,
                response_deserializer=scythe__pb2.StreamDelta.FromString,
                _registered_method=True)
        self.StreamSwarmDeltas = channel.unary_stream(
                '/scythe.v1.ScytheStreamService/StreamSwarmDeltas',
                request_serializer=scythe__pb2.StreamRequest.SerializeToString,
                response_deserializer=scythe__pb2.SwarmDelta.FromString,
                _registered_method=True)


class ScytheStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamClusters(self, request, context):
        """Server-streaming: push cluster topology snapshots as they change (~1 Hz).
        instance_id in StreamRequest scopes the stream to a single instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRFField(self, request, context):
        """Server-streaming: push live RF voxel fields at the requested LOD.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDeltas(self, request, context):
        """Server-streaming: push incremental node deltas for a single instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSwarmDeltas(self, request, context):
        """Server-streaming: push swarm intelligence deltas (silence_pressure,
        coherence, latent intent) only when values change.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScytheStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamClusters': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamClusters,
                    request_deserializer=scythe__pb2.StreamRequest.FromString,
                    response_serializer=scythe__pb2.StreamCluster.SerializeToString,
            ),
            'StreamRFField': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRFField,
                    request_deserializer=scythe__pb2.LodHint.FromString,
                    response_serializer=scythe__pb2.RFField.SerializeToString,
            ),
            'StreamDeltas': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDeltas,
                    request_deserializer=scythe__pb2.StreamRequest.FromString,
                    response_serializer=scythe__pb2.StreamDelta.SerializeToString,
            ),
            'StreamSwarmDeltas': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSwarmDeltas,
                    request_deserializer=scythe__pb2.StreamRequest.FromString,
                    response_serializer=scythe__pb2.SwarmDelta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scythe.v1.ScytheStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scythe.v1.ScytheStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScytheStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.ScytheStreamService/StreamClusters',
            scythe__pb2.StreamRequest.SerializeToString,
            scythe__pb2.StreamCluster.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRFField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.ScytheStreamService/StreamRFField',
            scythe__pb2.LodHint.SerializeToString,
            scythe__pb2.RFField.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDeltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.ScytheStreamService/StreamDeltas',
            scythe__pb2.StreamRequest.SerializeToString,
            scythe__pb2.StreamDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSwarmDeltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.ScytheStreamService/StreamSwarmDeltas',
            scythe__pb2.StreamRequest.SerializeToString,
            scythe__pb2.SwarmDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuthServiceStub(object):
    """─── AuthService ──────────────────────────────────────────────────────────────
    Obtain session tokens over gRPC — no prior token required.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/scythe.v1.AuthService/Login',
                request_serializer=scythe__pb2.LoginRequest.SerializeToString,
                response_deserializer=scythe__pb2.LoginResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """─── AuthService ──────────────────────────────────────────────────────────────
    Obtain session tokens over gRPC — no prior token required.

    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=scythe__pb2.LoginRequest.FromString,
                    response_serializer=scythe__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scythe.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scythe.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """─── AuthService ──────────────────────────────────────────────────────────────
    Obtain session tokens over gRPC — no prior token required.

    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scythe.v1.AuthService/Login',
            scythe__pb2.LoginRequest.SerializeToString,
            scythe__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OperatorStreamStub(object):
    """─── OperatorStream ───────────────────────────────────────────────────────────
    Bidi mux with anonymous warm-start and in-place auth upgrade.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/scythe.v1.OperatorStream/Connect',
                request_serializer=scythe__pb2.OperatorEnvelope.SerializeToString,
                response_deserializer=scythe__pb2.OperatorEnvelope.FromString,
                _registered_method=True)
        self.StreamView = channel.unary_stream(
                '/scythe.v1.OperatorStream/StreamView',
                request_serializer=scythe__pb2.OperatorView.SerializeToString,
                response_deserializer=scythe__pb2.OperatorEnvelope.FromString,
                _registered_method=True)


class OperatorStreamServicer(object):
    """─── OperatorStream ───────────────────────────────────────────────────────────
    Bidi mux with anonymous warm-start and in-place auth upgrade.

    """

    def Connect(self, request_iterator, context):
        """Full-duplex: client sends AuthRequest/Command; server pushes
        cluster/swarm/backpressure/field envelopes.
        No token required to start; server serves LOD-0 anonymous view
        until an AuthRequest envelope arrives and upgrades the stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamView(self, request, context):
        """Unary subscription: specify layers → server pushes matching envelopes.
        Requires valid authorization metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperatorStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=scythe__pb2.OperatorEnvelope.FromString,
                    response_serializer=scythe__pb2.OperatorEnvelope.SerializeToString,
            ),
            'StreamView': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamView,
                    request_deserializer=scythe__pb2.OperatorView.FromString,
                    response_serializer=scythe__pb2.OperatorEnvelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scythe.v1.OperatorStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scythe.v1.OperatorStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperatorStream(object):
    """─── OperatorStream ───────────────────────────────────────────────────────────
    Bidi mux with anonymous warm-start and in-place auth upgrade.

    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/scythe.v1.OperatorStream/Connect',
            scythe__pb2.OperatorEnvelope.SerializeToString,
            scythe__pb2.OperatorEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.OperatorStream/StreamView',
            scythe__pb2.OperatorView.SerializeToString,
            scythe__pb2.OperatorEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TakMLServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/scythe.v1.TakMLService/Infer',
                request_serializer=scythe__pb2.TakMLRequest.SerializeToString,
                response_deserializer=scythe__pb2.TakMLResponse.FromString,
                _registered_method=True)


class TakMLServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Unary: proxy a single feature vector to the instance KServe backend.
        NOTE: StreamInfer was removed — real event-driven streaming requires the
        TAK-ML async inference pipeline to be wired as an event source first.
        Use OperatorStream.Connect for ModelStatus health push envelopes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TakMLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=scythe__pb2.TakMLRequest.FromString,
                    response_serializer=scythe__pb2.TakMLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scythe.v1.TakMLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scythe.v1.TakMLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TakMLService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scythe.v1.TakMLService/Infer',
            scythe__pb2.TakMLRequest.SerializeToString,
            scythe__pb2.TakMLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReconEntityStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEntities = channel.unary_stream(
                '/scythe.v1.ReconEntityStream/StreamEntities',
                request_serializer=scythe__pb2.ReconStreamRequest.SerializeToString,
                response_deserializer=scythe__pb2.EntityPatch.FromString,
                _registered_method=True)


class ReconEntityStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamEntities(self, request, context):
        """Server-streaming: emit EntityPatch events as entities are discovered or
        enriched.  Starts with a snapshot of existing entities (op=upsert),
        then streams incremental mutations as they arrive from ingest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReconEntityStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEntities': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEntities,
                    request_deserializer=scythe__pb2.ReconStreamRequest.FromString,
                    response_serializer=scythe__pb2.EntityPatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scythe.v1.ReconEntityStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scythe.v1.ReconEntityStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReconEntityStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.ReconEntityStream/StreamEntities',
            scythe__pb2.ReconStreamRequest.SerializeToString,
            scythe__pb2.EntityPatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControlPathStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamControlPaths = channel.unary_stream(
                '/scythe.v1.ControlPathStream/StreamControlPaths',
                request_serializer=scythe__pb2.ControlPathStreamRequest.SerializeToString,
                response_deserializer=scythe__pb2.ControlPathPatch.FromString,
                _registered_method=True)


class ControlPathStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamControlPaths(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPathStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamControlPaths': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamControlPaths,
                    request_deserializer=scythe__pb2.ControlPathStreamRequest.FromString,
                    response_serializer=scythe__pb2.ControlPathPatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scythe.v1.ControlPathStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scythe.v1.ControlPathStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPathStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamControlPaths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scythe.v1.ControlPathStream/StreamControlPaths',
            scythe__pb2.ControlPathStreamRequest.SerializeToString,
            scythe__pb2.ControlPathPatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
