# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pb/event.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pb/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epb/event.proto\x12\x02pb\"$\n\x06\x45ntity\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"g\n\x05\x45vent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x1c\n\x08\x65ntities\x18\x03 \x03(\x0b\x32\n.pb.Entity\x12\r\n\x05\x65\x64ges\x18\x04 \x03(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"\'\n\nEventBatch\x12\x19\n\x06\x65vents\x18\x01 \x03(\x0b\x32\t.pb.Event\")\n\x08\x45ventAck\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t2?\n\rEventStreamer\x12.\n\x0cStreamEvents\x12\x0e.pb.EventBatch\x1a\x0c.pb.EventAck(\x01\x42$Z\"github.com/yourorg/eve-streamer/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"github.com/yourorg/eve-streamer/pb'
  _globals['_ENTITY']._serialized_start=22
  _globals['_ENTITY']._serialized_end=58
  _globals['_EVENT']._serialized_start=60
  _globals['_EVENT']._serialized_end=163
  _globals['_EVENTBATCH']._serialized_start=165
  _globals['_EVENTBATCH']._serialized_end=204
  _globals['_EVENTACK']._serialized_start=206
  _globals['_EVENTACK']._serialized_end=247
  _globals['_EVENTSTREAMER']._serialized_start=249
  _globals['_EVENTSTREAMER']._serialized_end=312
# @@protoc_insertion_point(module_scope)
