steps:
  # Import builder if exists.
  # Note: the reason to use bash is to be able to return an exit code 0 even if
  # the docker image doesn't exist yet.
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker pull ${_IMAGE_REPO_NAME}/${PROJECT_ID}/cli-releaser || exit 0

  # Build a modified version of the python image, including tools to build and
  # release the Kaggle CLI.
  # Use the previous built image as cache.
  - name: gcr.io/cloud-builders/docker
    id: cli-releaser-build
    dir: tools/releases
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_IMAGE_REPO_NAME}/${PROJECT_ID}/cli-releaser
      - --cache-from
      - ${_IMAGE_REPO_NAME}/${PROJECT_ID}/cli-releaser
      - .

  # Get the GitHub access token from Secret Manager.
  # The token is used to talk to GitHub API, specifically to create a release.
  - name: gcr.io/cloud-builders/gcloud
    id: github-token
    entrypoint: bash
    args: 
    - -c
    - gcloud secrets versions access latest --secret=kaggleteam-github-access-token > /root/github_token
    volumes:
    - name: root
      path: /root

  # Get the pypi token from Secret Manager, and create the ~/.pypirc file.
  - name: gcr.io/cloud-builders/gcloud
    id: create-credentials-pypirc
    entrypoint: bash
    args:
      - -c
      - |
        token_test=$(gcloud secrets versions access latest --secret=test-pypi-token)
        token=$(gcloud secrets versions access latest --secret=pypi-token)
        cat >~/.pypirc <<EOL
        [distutils]
        index-servers =
          pypi
          pypitest
        [pypi]
        repository: https://upload.pypi.org/legacy/
        username=__token__
        password=${token}
        [pypitest]
        repository: https://test.pypi.org/legacy/
        username=__token__
        password=${token_test}
        EOL
    volumes:
      - name: root
        path: /root

  - name: ${_IMAGE_REPO_NAME}/${PROJECT_ID}/cli-releaser
    id: generate-cli
    waitFor: ['cli-releaser-build']
    entrypoint: bash
    args:
      - -c
      - |
        rm -f kaggle
        cp -r src/kaggle .
        python3 -m pip install build --break-system-packages
        python3 -m build
        # Move the built CLI to a volume that will survive to next steps.
        mv dist /root/
    volumes:
      - name: root
        path: /root

  # Create a release on GitHub.
  # The `hub` image has been built previously in the project:
  # $ git clone https://github.com/GoogleCloudPlatform/cloud-builders-community.git
  # $ cd cloud-builders-community/hub
  # $ gcloud builds submit
  - name: us-docker.pkg.dev/$PROJECT_ID/tools/hub
    id: release
    waitFor: ['generate-cli', 'github-token']
    entrypoint: bash
    env:
    - GITHUB_USER=kaggle
    - GITHUB_REPOSITORY=kaggle-cli
    - HUB_PROTOCOL=https
    args:
    - -c
    # $$RELEASE_VERSION (two '$') is not a typo. This is to avoid conflicts with Google Cloud Build substitutions.
    - |
      export RELEASE_VERSION=`grep __version__ src/kaggle/__init__.py | sed -E "s/.*['\"]([^'\"]+)['\"].*/\1/"`
      echo "Preparing release for version $$RELEASE_VERSION"
      export GITHUB_TOKEN=$(</root/github_token)
      if [ "${_PYPY_REPOSITORY}" = "pypi" ]; then
        echo "Creating a release on GitHub..."
        git clone https://github.com/kaggle/kaggle-cli.git release-repo
        cd release-repo
        hub release create -m "release v$$RELEASE_VERSION" "v$$RELEASE_VERSION"
      else
        echo "Skipping GitHub release, this is a release to pypitest"
      fi
    volumes:
    - name: root
      path: /root

  # Release package to pypi.
  - name: ${_IMAGE_REPO_NAME}/${PROJECT_ID}/cli-releaser
    id: release-pypi
    waitFor: ['generate-cli', 'create-credentials-pypirc']
    entrypoint: bash 
    args:
    - -c
    - |
      twine upload /root/dist/* --repository ${_PYPY_REPOSITORY}
    volumes:
    - name: root
      path: /root

images: ["${_IMAGE_REPO_NAME}/${PROJECT_ID}/cli-releaser"]

substitutions:
  _IMAGE_REPO_NAME: us-docker.pkg.dev/kaggle-cicd/tools
  _PYPY_REPOSITORY: pypitest