steps:
# Check substitutions / Pull cache
- name: 'gcr.io/cloud-builders/docker'
  id: 'check_substitutions'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull us-docker.pkg.dev/$PROJECT_ID/tools/cli-builder:${_PYTHON_VERSION} || exit 0
  waitFor: ['-']

# Build a modified version of the python image that includes hatch.
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-hatch-image'
  waitFor: ['check_substitutions']
  dir: 'tools/cicd'
  args:
  - build
  - -f
  - Dockerfile
  - -t
  - us-docker.pkg.dev/$PROJECT_ID/tools/cli-builder:${_PYTHON_VERSION}
  - --cache-from
  - us-docker.pkg.dev/$PROJECT_ID/tools/cli-builder:${_PYTHON_VERSION}
  - --build-arg
  - PYTHON_VERSION=${_PYTHON_VERSION}
  - .

# Run unit tests
- name: us-docker.pkg.dev/$PROJECT_ID/tools/cli-builder:${_PYTHON_VERSION}
  id: tests
  env:
  - 'HOME=/builder/home/tests'
  args:
  - run
  - test:pytest
  waitFor: ['build-hatch-image']

# Run lint
- name: us-docker.pkg.dev/$PROJECT_ID/tools/cli-builder:${_PYTHON_VERSION}
  id: lint
  env:
  - 'HOME=/builder/home/lint'
  args:
  - run
  - lint:all
  waitFor: ['build-hatch-image']

# Download secrets for integration tests (only on main branch)
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'download-secrets'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret=integration-tests --project=464139560241 > /root/secrets.sh
  volumes:
  - name: 'root'
    path: /root
  waitFor: ['-']

# Run integration tests (only on main branch)
- name: us-docker.pkg.dev/$PROJECT_ID/tools/cli-builder:${_PYTHON_VERSION}
  id: integration-tests
  entrypoint: 'bash'
  env:
  - 'HOME=/builder/home/integration'
  args:
  - '-c'
  - |
    export KAGGLE_USERNAME
    export KAGGLE_KEY
    if [ -f /root/secrets.sh ]; then
      source /root/secrets.sh
    else
      echo "Secrets file not found!"
      exit 1
    fi
    hatch run test:integration
  volumes:
  - name: 'root'
    path: /root
  waitFor: ['build-hatch-image', 'download-secrets']

images:
- us-docker.pkg.dev/$PROJECT_ID/tools/cli-builder:${_PYTHON_VERSION}

substitutions:
  _PYTHON_VERSION: '3.11'
